language: python
python: '2.7'
sudo: required
env:
  #matrix:
#  - ANSIBLE_VERSION=latest
#  - ANSIBLE_VERSION=1.4
#  - ANSIBLE_VERSION=1.4.1
#  - ANSIBLE_VERSION=1.4.2
#  - ANSIBLE_VERSION=1.4.3
#  - ANSIBLE_VERSION=1.4.4
#  - ANSIBLE_VERSION=1.4.5
#  - ANSIBLE_VERSION=1.5.1
#  - ANSIBLE_VERSION=1.5.2
#  - ANSIBLE_VERSION=1.5.3
#  - ANSIBLE_VERSION=1.5.4
#  - ANSIBLE_VERSION=1.5.5
#  - ANSIBLE_VERSION=1.6
#  - ANSIBLE_VERSION=1.6.1
#  - ANSIBLE_VERSION=1.6.2
#  - ANSIBLE_VERSION=1.6.3
#  - ANSIBLE_VERSION=1.6.4
#  - ANSIBLE_VERSION=1.6.5
#  - ANSIBLE_VERSION=1.6.6
#  - ANSIBLE_VERSION=1.6.7
#  - ANSIBLE_VERSION=1.6.8
#  - ANSIBLE_VERSION=1.6.9
#  - ANSIBLE_VERSION=1.6.10
#  - ANSIBLE_VERSION=1.7
#  - ANSIBLE_VERSION=1.7.1
#  - ANSIBLE_VERSION=1.7.2
#  - ANSIBLE_VERSION=1.8
#  - ANSIBLE_VERSION=1.8.1
#  - ANSIBLE_VERSION=1.8.2
#  - ANSIBLE_VERSION=1.8.3
#  - ANSIBLE_VERSION=1.8.4
#  - ANSIBLE_VERSION=1.9.0.1
#  - ANSIBLE_VERSION=1.9.1
  - OS_TYPE=centos OS_VERSION=6 ANSIBLE_VERSION=1.9.2
  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=1.9.2
  - OS_TYPE=ubuntu_lts OS_VERSION=12 ANSIBLE_VERSION=1.9.2
  - OS_TYPE=ubuntu_lts OS_VERSION=14 ANSIBLE_VERSION=1.9.2
#  - OS_TYPE=fedora OS_VERSION=22

branches:
  only:
  - master
#  - stable

services:
  - docker

before_install:
  - docker pull weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION}

script:
 # Run tests in Container
 - docker run --rm=true -v `pwd`:/ansible-nginx:rw weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION} /bin/bash -c "/ansible-nginx/tests/test-in-docker-image.sh ${OS_TYPE} ${OS_VERSION} ${ANSIBLE_VERSION}"

notifications:
  email: false
#  hipchat:
#    rooms:

